### ISSUE TITLE
Overwrite should be false by default

### ISSUE THREAD

**Issue by jhliberty** [frostme/sails-seed#11]
And enabled by `overwrite: true`

**Comment by jhliberty** [comment]
Especially since every time the sails server is lifted it'll run the seed again causing the ids to be incremented.

**Comment by frostme** [comment]
i actually agree with this. Once I get time I'll try to get this out (or  a pull request). But I agree that overwrite should be false by default. When I created the module, I was using it for a development environment, where data was supposed to be sporadic (and overwrite a lot). But in a prod env, thats absolutely not what you want haha

**Comment by frostme** [comment]
fixed this in version 4.1. And published. Overwrite by default is now false.

**Comment by jhliberty** [comment]
![](https://media.giphy.com/media/5xrkJe3IJKSze/giphy.gif)

**Comment by frostme** [comment]
best...comment...ever. YAS!
