### ISSUE TITLE
 Cannot read property 'active' of undefined`

### ISSUE THREAD

**Issue by throll** [frostme/sails-seed#19]
I can't launch sails anymore (cf error message below), maybe i missed something in configuration ?

`if(sails.models[model].seed && !(sails.config.seeds[model].active === false)){
                                                                ^
TypeError: Cannot read property 'active' of undefined`

**Comment by frostme** [comment]
hello @throll . Sorry that that has happened, what does your config/seeds.js file look like?

**Comment by frostme** [comment]
Found the issue, thanks for pointing this out. Fix in PR #20 publishing out v0.4.5

**Comment by throll** [comment]
Thanks and glad to help !
