### ISSUE TITLE
Does not seed any data

### ISSUE THREAD

**Issue by Clan-Utility** [frostme/sails-seed#5]
It says:

debug: Seeding User...
debug: User seed planted
info: Your seeds are ready to grow!
info: Welcome to the Sails console.

But when I run User.find().exec(console.log), it shows 
undefined
sails> null []

Btw, on your homepage, it says config/seed.js. But it should be config/seeds.js (sails v0.11.0)

**Comment by frostme** [comment]
Thank you for the feedback. I have changed the README to display config/seeds.js.
Would you mind providing a representation of your config/seeds.js file as well as what version of sails you are using?

**Comment by Clan-Utility** [comment]
This is my User.js file:

    var User = {
         schema: true,

         attributes: {
               username  : { type: 'string'},
               email     : { type: 'email'},
               name: { type: 'string' },
               gender: { type: 'boolean' }
          }
     };
     module.exports = User;
And this the config/seeds.js file

    module.exports.seeds = {
       user: [
         {
             username: 'Luke',
             email:  'a@a.net',
             name: 'Luke Skywalker',
             gender: true
        },
        {
             username: 'Darth',
             email:  'a@a.net',
             name: 'Darth Vader',
             gender: true
        }
     ]
    }

**Comment by frostme** [comment]
Ah yes, I was able to reproduce the issue. I will look into it tonight and should have a new release out to npm before the end of the weekend (8/9). Thanks for the heads up, I will keep you updated once I pushed out the new release.

**Comment by frostme** [comment]
In the MASSIVE amount of researching I conducted ;) The sails-seed module has the incorrect function use of _.isUndefined on the overwrite and unique values in your config/seeds.js. I have merged the commit to fix, will push out a new release of 0.3.1. Thanks for the heads up.

**Comment by frostme** [comment]
@Clan-Utility I published the 0.3.1 release and your data should now be seeding,
