### ISSUE TITLE
Config option to disable hook? 

### ISSUE THREAD

**Issue by facultymatt** [frostme/sails-seed#7]
Is it possible to disable the seed hook via config? This would be useful for testing.

**Comment by frostme** [comment]
I think that's a great idea. Would the ability to add a disable config option to disable all seeding and an active option per model to be able to disable down to the model be useful?

**Comment by frostme** [comment]
I have provided both options now. As well as updated documentation. I've also published this to npm as v0.4.0 thanks for bringing this up!

**Comment by facultymatt** [comment]
Fantastic, great addition!
